/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class EventSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'endDate',
    'id',
    'startDate',
    'title',
    'type',
    'updatedAt',
  ] as const
  $columns = EventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare title: string
  @column()
  declare type: 'school' | 'company' | 'holiday' | 'exam' | 'other'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
